import React from "react";
import "./globals.css"; // Add any global styles here
import LoginForm from "./components/LoginForm";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <LoginForm />
        {children}
      </body>
    </html>
  );
}
